# Docs and examples to use:
# https://docs.travis-ci.com/user/languages/android
# http://panavtec.me/continous-integration-on-android-with-travis-ci
# https://github.com/codecov/example-android/blob/master/.travis.yml
# https://github.com/codepath/android_guides/wiki/Setting-up-Travis-CI
# http://stackoverflow.com/questions/34621124/using-travis-ci-with-android
sudo: required
language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-24
    - ANDROID_ABI=armeabi-v7a
    - ADB_INSTALL_TIMEOUT=8 # minutes (2 minutes by default)
android:
  components:
  - tools
  - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
  - platform-tools
  - build-tools-24.0.2
  - android-24
  - extra-android-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  # http://stackoverflow.com/questions/33820638/travis-yml-gradlew-permission-denied
  - chmod +x gradlew
before_script:
  - uname -a
  - android list targets
  - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
script:
  - ./gradlew build assembleAndroidTest
  - android-wait-for-emulator
  # Previous command seems to end too early, so wait a bit more
  # On multilined commands: https://gitlab.com/gitlab-org/gitlab-ci/issues/258 and http://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines
  - |
    while ! adb shell getprop init.svc.bootanim; do
      echo Waiting for boot animation to end
      sleep 10
    done
  # Another method. Should print SDK version number to console
  # See http://stackoverflow.com/questions/28195080/unknown-api-level-error-when-trying-to-run-instrumentation-test
  - |
    while ! adb shell getprop ro.build.version.sdk; do
      echo Waiting for ro.build.version.sdk value from device
      sleep 10
    done
  - adb devices
  - adb shell input keyevent 82 &
  # See http://stackoverflow.com/questions/21294945/error-unable-to-find-instrumentation-info-for-componentinfo
  # Instead of this (which doesn't give any output during tests execution):
  # - ./gradlew connectedCheck -PdisablePreDex --continue --stacktrace --debug
  # run:
  - ./gradlew :app:installDebugAndroidTest :app:installDebug
  #
  # The below line causes Process crash due to absense of video device
  #- adb shell am instrument -w -r -e debug false org.andstatus.app.tests/android.test.InstrumentationTestRunner
  #
  # Run only tests, marked with a special annotation:
  # See https://developer.android.com/reference/android/test/InstrumentationTestRunner.html
  - adb shell am instrument -w -r -e annotation org.andstatus.app.context.Travis org.andstatus.app.tests/android.test.InstrumentationTestRunner
  # For testing one method only:
  # - adb shell am instrument -w -r -e debug false -e class org.andstatus.app.msg.ActAsUserTest#testActAsUser org.andstatus.app.tests/android.test.InstrumentationTestRunner
after_success:
  - ./gradlew sonarqube -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN -Dsonar.verbose=true
